[build]
  # public directory
  publish = "dist"
  # command on build
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev:app"

# Required for react router.
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
